### ISSUE TITLE
Screen flashes to black whenever Tabby renders (Windows 11)

### ISSUE THREAD

**Issue by TJC** [Eugeny/terminus#10602]
**Describe the problem**:
I've been using Tabby on Windows 10 successfully. Yesterday I upgraded to Windows 11, and now I am experiencing this bug. I have upgraded to the latest Tabby (1.0.223) and latest Nvidia drivers (580.88) but the issue remains.

The bug is that whenever Tabby renders changes to its window, my entire desktop goes black for about two seconds, then returns to normal. 

If Tabby is open and nothing is happening in the window, it's fine. If i start typing, the screen starts flashing to black.

If Tabby is open and another window is covering it, then I alt-tab to Tabby, my screen flashes black.

I know this sounds like a general Windows 11 or Nvidia driver issue, but it's only happening with Tabby. I can play games or using Google Chrome or File Explorer or Command Prompt etc just fine.

**To Reproduce**:
* Have my computer (AMD 5700X and Nvidia 4070 Ti) with a several-years-old Windows 10 install on it.
* Be forced to upgrade to Windows 11 by Microsoft
* Open Tabby and immediately have screen flash to black for a couple of seconds.
* Swear and cry

** Apologies **

I know this isn't a very useful bug report, and it'll be hard to reproduce. But I thought if I open it, at least anyone else in the same boat can join in. Maybe if it turns out to be an issue affecting many people we can figure something out.

**Comment by luanfernandes** [comment]
I think this is an AMD issue. check #10773 . I'm having the same issues, still testing but I think it stopped.

**Comment by chrismhinds** [comment]
I had a very similar issue with a more recent PC build.  I have an MSI motherboard (MAG 870XE Tomahawk MS-7E59) and an NVIDIA Geforce RTX 5070 TI.  When I would use Tabby, the screen would flicker, the desktop icons would reset (flash to a white then come back as normal), and then the Tabby screen would go to black.  The only way I could fix it was to exit Tabby and start over - which is pretty crummy when you're in the middle of coding and at a certain directory, etc.  I reinstalled Windows, and that didn't solve the issue.  What DID solve it, however, was disabling the integrated video card on my motherboard.  I rebooted into BIOS and disabled it, rebooted again, and Tabby stopped "fading to black" (music reference).  Apparently the integrated video card and my aftermarket NVIDIA card weren't playing well together, and it ("it" being the windows display) kept crashing.  So, while perhaps Tabby could handle video resets better, my issue was with my conflicting video cards, not with Tabby.

**Comment by karl-xing** [comment]
> I think this is an AMD issue. check [#10773](https://github.com/Eugeny/tabby/issues/10773) . I'm having the same issues, still testing but I think it stopped.

[#10773](https://github.com/Eugeny/tabby/issues/10773) happened on my laptop with intel and nvidia.

**Comment by richard-scott** [comment]
I get this in v1.0.233 still.

**Comment by chvrs12** [comment]
annoying asl issue, fixed now.. atleast I hope its fixed for everyone having this

**Comment by richard-scott** [comment]
Still the same in 1.0,235. Has the fix been rolled into a release yet?

**Comment by chvrs12** [comment]
> Still the same in 1.0,235. Has the fix been rolled into a release yet?

seems like its not pushed to release, compile tabby yourself, uninstall tabby and reinstall it should be fixed

**Comment by richard-scott** [comment]
This is still broken on 1.0.236-nightly.0

**Comment by chvrs12** [comment]
> This is still broken on 1.0.236-nightly.0

which gpu are you on?

also make sure to make tabby run on your main gpu incase you have 2

**Comment by richard-scott** [comment]
AMD Ryzen 7 7730U with Radeon Graphics.
I have disabled GPU acceleration features for now.
