### ISSUE TITLE
Updating SSH and OpenSSL on Ubuntu 22.04, can not connect SFTP.

### ISSUE THREAD

**Issue by JackHuang90** [Eugeny/terminus#10938]
**Describe the problem**:
After updating SSH and OpenSSL for Ubuntu 22.04, SFTP kept showing "Connectting". 

OpenSSH_10.2p1, OpenSSL 3.5.4 30 Sep 2025

How to find the Tabby log file?

<img width="738" height="147" alt="Image" src="https://github.com/user-attachments/assets/c8d9fc1d-0cd3-429b-a8b0-d02746a4913f" />

<img width="634" height="1464" alt="Image" src="https://github.com/user-attachments/assets/96c789ab-3214-4fe6-b33b-bb0d52793f3f" />

**To Reproduce**:
1. Updating SSH and OpenSSL for Ubuntu 22.04
Version: OpenSSH_10.2p1, OpenSSL 3.5.4 30 Sep 2025
2. Connect SSH, open SFTP window.
3. I can connect by WinSCP 、MobaXterm、XFTP，but can not connect by Tabby.

**Comment by Eugeny** [comment]
Should be fixed in the latest nightly

**Comment by shaolinyang2009** [comment]
I tried nigthly 230, the issue seems not fixed.

**Comment by JackHuang90** [comment]
> Should be fixed in the latest nightly
@Eugeny 
tabby-1.0.231-nightly.0-setup-x64.exe not fixed. Time: 2026/1/16
