### ISSUE TITLE
Terminus Doesn't Open

### ISSUE THREAD

**Issue by vysecurity** [Eugeny/terminus#1175]
Terminus doesn't open at all.

No process in task menu, so it is not off screen either.

Process is in background, but doesn't launch anything.

**Comment by vysecurity** [comment]
Windows by the way.

10.0.18922 N/A Build 18922

**Comment by yanke1311** [comment]
deepin using the latest release also cannot open at all

**Comment by dizzu** [comment]
Same problem here. Windows 10 v1803 Build 17134

**Comment by ArturoRis** [comment]
Same problem on  Linux Mint 18.3 Sylvia.
When opening from terminal this happens (see screenshot below) and then it quits.

![image](https://user-images.githubusercontent.com/22544826/60655700-80f9c100-9e4e-11e9-9a44-6fc740863554.png)

**Comment by yanke1311** [comment]
still cannot open it when i reinstall to 1.0.84, my os is deepin; and my win10 is OK? so strange～

**Comment by yanke1311** [comment]
@Eugeny

**Comment by ArturoRis** [comment]
Nothing changed for me too: I've just tried 1.0.84

**Comment by gdmad** [comment]
After upgrading to version 1.0.84, stopped running.
After deleting all the folders (..\AppData\Local\terminus-updater and ..\AppData\Roaming\Terminus) and reinstalling, started once, after did not start.
Windows 10 Pro v1903 Build 18362.175

**Comment by kevintsengtw** [comment]
1.0.84 and 1.0.85 same issues

**Comment by ArturoRis** [comment]
It is fixed in 1.0.85 :D

**Comment by edermi** [comment]
Still doesn't work on Windows 10 1903 with the portable version
