### ISSUE TITLE
safevalue must use [property]=binding

### ISSUE THREAD

**Issue by nipeone** [Eugeny/terminus#1769]
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: altair, clickable-links, quick-cmds, relaxed-theme, save-output, scrollbar, shell-selector, theme-gruvbox, theme-hype, theme-windows10, title-control

**Comment by Eugeny** [comment]
Fixed in shell-selector, but the quick-cmds author hasn't releasing a fixed version yet.

**Comment by 360path** [comment]
I still have this on the button on the top right:
![Terminus_2020-03-04_15-42-03](https://user-images.githubusercontent.com/671319/75890604-e31c2300-5e2e-11ea-8a17-f92c1ef810b7.png)

**Comment by Eugeny** [comment]
Please upgrade the shell-selector plugin

**Comment by 360path** [comment]
Unfortunately there is no update button for the shell-selector plugin:

![Terminus_2020-03-04_16-54-25](https://user-images.githubusercontent.com/671319/75897510-f6cc8700-5e38-11ea-8879-567ff922c242.png)

**Comment by Eugeny** [comment]
Actually, shell-selector is obsolete now - the same functionality is provided by the Profiles button (next to the "new tab" button).

**Comment by Deathtech-00** [comment]
Can we remove the shell-selector plugin without repercussion then?
