### ISSUE TITLE
Ssh connection is still there, the tab is not displayed

### ISSUE THREAD

**Issue by sotex** [Eugeny/terminus#1784]
Version: 1.0.91
Platform: win32 10.0.19013
Plugins: relaxed-theme, theme-gruvbox, theme-hype, theme-windows10

![图片](https://user-images.githubusercontent.com/16911453/69126549-6e251780-0ae3-11ea-8067-ca2cd383e63c.png)

**Comment by Eugeny** [comment]
This should be fixed in the latest nightly.

**Comment by amirhfarzaneh** [comment]
I still see the connections lingering in the remote server with `w` command when I close the tab with ssh connection:

Version: 1.0.120
Platform: Mac OS Catalina 10.15.6
Plugins: relaxed-theme

**Comment by rpotvin** [comment]
Same issue as amirhfarzaneh, the connection does not close after close the tab. 

1.0.127
Platform: Windows 10
Plugins: defaults
I use ssh-agent on windows
