### ISSUE TITLE
Not working key up/down on new SSH connection selector (28c58d4)

### ISSUE THREAD

**Issue by siccous** [Eugeny/terminus#2294]
Hello Eugeny,

first thank you very much for implementing this new SSH connection selector 👏.

I already tried it and it partially works for me. I can search and start the connection with enter, but I suppose I should also be able to navigate through the results with key up/down and that's not working for me.

Platform: Windows 10 x64
Plugins: Hype (my own updated version)

Thank you, Sicco

**Comment by Eugeny** [comment]
I've just fixed it in yesterday's nightly build, thanks for the report!

**Comment by siccous** [comment]
Hello again,

I've made my own build two hours ago, it is built on  current master, so I don't think it is fixed.

Or there are some commits which are not yet on the master branch?

**Comment by Eugeny** [comment]
Nevermind - found and fixed it!
