### ISSUE TITLE
No support for Ed25519 with Built-in SSH Plugin

### ISSUE THREAD

**Issue by karaface** [Eugeny/terminus#272]
Tried to connect using my Ed25519 key with the SSH plugin but was told my authentication key type was not supposed. 
![capture](https://user-images.githubusercontent.com/6392300/34646606-828698a6-f321-11e7-8050-cf5a7aed01f8.PNG)

Worked just fine on WSL (Fedora).

**Comment by angristan** [comment]
Then I will comment, because ed25519 is the future.

**Comment by nimrod7137** [comment]
I was poking around the open issues and it looks like ed25519 was finally added to the ssh2 library a few days ago with v0.8.3 and node v12.0.0. 

Hopefully the changes can get pulled in soon, using my key natively instead of having to ssh from my WSL instance.

Here's the link to the offending [upstream issue](https://github.com/mscdex/ssh2/issues/352#issuecomment-486511390) from their github repository evev though it's referenced in the comment above.

Thanks and good luck on the project

**Comment by Eugeny** [comment]
Fixed via https://github.com/Eugeny/terminus/pull/883 and https://github.com/Eugeny/terminus/pull/878

**Comment by tchadelicard** [comment]
With the latest version of Terminus, I still can't use my ED25519 SSH keys.

Here's a screenshot of my error:
![image](https://user-images.githubusercontent.com/22417050/59699425-d77dc300-91f1-11e9-9968-b13faf5d8948.png)

Here's a screenshot of the version I'm running:
![image](https://user-images.githubusercontent.com/22417050/59699535-06943480-91f2-11e9-8c2c-fcdacdf1b479.png)

**Comment by nimrod7137** [comment]
> With the latest version of Terminus, I still can't use my ED25519 SSH keys.
> 
> Here's a screenshot of my error:
> ![image](https://user-images.githubusercontent.com/22417050/59699425-d77dc300-91f1-11e9-9968-b13faf5d8948.png)
> 
> Here's a screenshot of the version I'm running:
> ![image](https://user-images.githubusercontent.com/22417050/59699535-06943480-91f2-11e9-8c2c-fcdacdf1b479.png)

I think you're supposed to use OpenSSH format instead of Putty. I'm still getting errors when attempting to use my OpenSSH ED25519 keys.

![Terminus_2019-06-20_07-40-52](https://user-images.githubusercontent.com/5772212/59846973-4dd40f80-932f-11e9-87d3-e0030ce7efdd.png)

![Terminus_2019-06-20_07-42-15](https://user-images.githubusercontent.com/5772212/59846979-50cf0000-932f-11e9-8d3f-dfb87ede4041.png)

**Comment by tchadelicard** [comment]
When I convert my SSH key to OpenSSH format with PuttyGen, my key is recognized but my passphrase is not parsed.
![image](https://user-images.githubusercontent.com/22417050/60346375-4958c800-99bb-11e9-923b-aea331c96979.png)
