### ISSUE TITLE
reconnect bug

### ISSUE THREAD

**Issue by ZehuanZhang** [Eugeny/terminus#2873]
the latest version (1.0.116) has a bug that when a connection is lost and reconnected the keypress is not working (console could not accept any inputs). (just test on two machines and the SSH connection is configured in Settings)

**Comment by ZehuanZhang** [comment]
this bug is fixed in the latest version 1.0.117

**Comment by snehbansal** [comment]
This is still reproducible on 1.0.120, though the frequency is not 100%. Reconnecting the same tab does not change anything. One needs to open an entirely new tab for the same SSH session to get this working again.
