### ISSUE TITLE
Tabs on bottom no longer shown

### ISSUE THREAD

**Issue by raoul-thill** [Eugeny/terminus#3186]
Since the release of v1.0.121, tabs are no longer shown when selecting bottom location. On top, left and right are working as before.

**Comment by wudisheng** [comment]
Same.

Also, the status bar of tmux / screen is out of the view, tried clearing customized CSS but it still problematic.

**Comment by dlazarov** [comment]
With the tabs at the bottom, they're out of view, and if they're on top, the cursor line is off the screen as well when you reach the bottom of the view.

![image](https://user-images.githubusercontent.com/6955442/101525369-e206bc00-3993-11eb-8a51-3bd64445a42d.png)

**Comment by Eugeny** [comment]
Fixed

**Comment by dlazarov** [comment]
@Eugeny I just installed version 122 and the tabs are still not shown at the bottom.
