### ISSUE TITLE
[Windows] Can't create terminal (or start with one)

### ISSUE THREAD

**Issue by SarcasmAppreciated** [Eugeny/terminus#444]
On Windows, sometimes I start Terminus and no terminal appears. I can't add terminals either via the '+' button (nothing happens on press).

I have to restart my PC and hope they showup on program startup.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Razoralpha** [comment]
Same issue, nothing on the console, not even in Verbose log level. The "+" gets the visual selection but nothing else happens, same for the main screens "+ New terminal" button.

I'm on a few days old Win10 with 1.0.0 alpha 58.

**Comment by capdiem** [comment]
ERROR Error: Uncaught (in promise): Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
    at resolvePromise (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at o (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\builtin-plugins\terminus-terminal\dist\index.js:162:825)
    at ZoneDelegate.invoke (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146:33)
    at ZoneDelegate.invoke (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137:33)
defaultErrorLogger @ D:\scoop\apps\terminus\1.0.0-alpha.58\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682

**Comment by Eugeny** [comment]
This should be fixed in the latest alpha - please check!

**Comment by thedewil** [comment]
The problem persists on alpha 59, FYI;

entry.ts:41 Starting with plugins: Array(15)
plugins.ts:151 Loading altair: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-altair\dist\index.js
plugins.ts:151 Loading clickable-links: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-clickable-links\dist\index.js
plugins.ts:151 Loading quick-cmds: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-quick-cmds\dist\index.js
plugins.ts:151 Loading scrollbar: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-scrollbar\dist\index.js
plugins.ts:151 Loading shell-selector: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-shell-selector\dist\index.js
plugins.ts:151 Loading theme-gruvbox: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-theme-gruvbox\dist\index.js
plugins.ts:151 Loading theme-hype: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-theme-hype\dist\index.js
plugins.ts:151 Loading theme-windows10: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-theme-windows10\dist\index.js
plugins.ts:151 Loading title-control: C:\Users\user\AppData\Roaming\terminus\plugins\node_modules\terminus-title-control\dist\index.js
plugins.ts:151 Loading community-color-schemes: C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-community-color-schemes\dist\index.js
plugins.ts:151 Loading core: C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-core\dist\index.js
plugins.ts:151 Loading plugin-manager: C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-plugin-manager\dist\index.js
plugins.ts:151 Loading settings: C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-settings\dist\index.js
plugins.ts:151 Loading ssh: C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-ssh\dist\index.js
internal/process/warning.js:18 (node:11672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
writeOut @ internal/process/warning.js:18
plugins.ts:151 Loading terminal: C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-terminal\dist\index.js
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-core\dist\index.js:218 [hostApp] Window ID: 1
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-core\dist\index.js:218 [main] v 1.0.0-alpha.59
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-core\dist\index.js:218 [updater] No updates
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682 ERROR Error: Uncaught (in promise): Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
    at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at o (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-terminal\dist\index.js:162:825)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146:33)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137:33)
defaultErrorLogger @ C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682 ERROR Error: Uncaught (in promise): Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
    at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:771:17)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:873:17
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137:33)
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:420:36)
    at Zone.runTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:188:47)
    at drainMicroTaskQueue (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:595:35)
defaultErrorLogger @ C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682 ERROR Error: Uncaught (in promise): Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
    at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at o (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-terminal\dist\index.js:288:825)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146:33)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137:33)
defaultErrorLogger @ C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682
2C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682 ERROR Error: Uncaught (in promise): Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
    at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at o (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-terminal\dist\index.js:162:825)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146:33)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137:33)
defaultErrorLogger @ C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682 ERROR Error: Uncaught (in promise): Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
    at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at o (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-terminal\dist\index.js:288:825)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146:33)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137:33)
defaultErrorLogger @ C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682
C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:1682 ERROR Error: Uncaught (in promise): Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

Error: Command failed: C:\WINDOWS\system32\wslconfig.exe /l

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
    at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:814:31)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:724:17
    at o (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\builtin-plugins\terminus-terminal\dist\index.js:288:825)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:388:26)
    at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146:33)
    at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:387:32)
    at Zone.run (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:138:43)
    at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\zone.js\dist\zone.js:421:31)
    at Object.onInvokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha59\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137:33)

**Comment by GhostChild** [comment]
same problem on alpha 59.

**Comment by Eugeny** [comment]
Please try the new alpha 60

**Comment by thedewil** [comment]
Problem still persists, only with a different error message:

ERROR Error: Uncaught (in promise): TypeError: V.trim is not a function
        TypeError: V.trim is not a function
            at b (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:85)
            at new F (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:85)
            at V (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:925)
            at new ZoneAwarePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:891)
            at f.<anonymous> (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:925)
            at Generator.next (<anonymous>)
            at i (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:925)
            at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:388)
            at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146)
            at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:387)
            at b (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:85)
            at new F (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:85)
            at V (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:925)
            at new ZoneAwarePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:891)
            at f.<anonymous> (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:925)
            at Generator.next (<anonymous>)
            at i (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:925)
            at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:388)
            at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146)
            at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:387)
            at resolvePromise (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:814)
            at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:724
            at o (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\builtin-plugins\terminus-terminal\dist\index.js:288)
            at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:388)
            at Object.onInvoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4146)
            at ZoneDelegate.invoke (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:387)
            at Zone.run (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:138)
            at C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:872
            at ZoneDelegate.invokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\zone.js\dist\zone.js:421)
            at Object.onInvokeTask (C:\Users\user\AppData\Local\terminus\app-1.0.0-alpha60\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:4137)

**Comment by Eugeny** [comment]
Any chance you could find out the exact location by clicking the source link in the trace and pretty-printing it?

**Comment by thedewil** [comment]
https://cl.ly/bb7d315d4aa4

**Comment by Eugeny** [comment]
It's the other one ("index.js:85")

**Comment by thedewil** [comment]
Sorry, here it is:

https://cl.ly/cb66faa1e6fb

**Comment by Eugeny** [comment]
Please try https://github.com/Eugeny/terminus/releases/tag/v1.0.0-alpha.61

**Comment by thedewil** [comment]
Fixed now, thanks a lot for quick resolution!
