### ISSUE TITLE
Ctrl+Shift+V Double Paste

### ISSUE THREAD

**Issue by ChaosZero112** [Eugeny/terminus#468]
Version: 1.0.0-alpha.61
Platform: win32 10.0.15063

Maybe just me, but on build 61 Ctrl+Shift+V for paste is producing a double paste every time.

The paste from the menu and right-click paste work correctly.

**Comment by NixNotCastey** [comment]
Ctrl+Shift+V is hardcoded shortcut, just change it in settings for something else and ctrl+shift+v will paste only once. This shortcut will work even if isn't set in options.

**Comment by wadewinningham** [comment]
I have the same issue only with Cmd-V for Mac. it double pastes. I tried removing and re-adding the hotkey but that did not work.

**Comment by jamesrweb** [comment]
I had the same issue even with a rebinding of the hotkey, seems to double paste on multiple shells also.

Date: _**09/12/2018**_
Terminus version: **_1.0.1_**
Shells used: **_Git-Bash, CMD_**
OS: **_windows 10 - version 1803 - Build 17134.441_**.

**Comment by Eugeny** [comment]
Are you guys using xterm as the terminal frontend?

**Comment by jamesrweb** [comment]
@Eugeny I am, yes.

**Comment by Eugeny** [comment]
It should be fixed in the latest release then

**Comment by barnumbirr** [comment]
Still happening with when using xterm as a terminal frontend in v.1.0.1. Works fine when using hterm.

Version: 1.0.1
Platform: win32 10.0.17763
Plugins: clickable-links, scrollbar
