### ISSUE TITLE
PsReadLine key handlers not working

### ISSUE THREAD

**Issue by Flueworks** [Eugeny/terminus#507]
I use Powershell Core 6.1.0 with PsReadline 2.0.0.
Some shortcuts does work, some does not:

Some that works:

Backspace        BackwardDeleteChar
Ctrl+h           BackwardDeleteChar
Ctrl+Home        BackwardDeleteLine
Ctrl+End         ForwardDeleteLine
Shift+Insert     Paste
Ctrl+LeftArrow   BackwardWord
Ctrl+r           ReverseSearchHistory
Tab              MenuComplete
Some that does not work:

Shift+Enter      AddLine
Ctrl+Backspace   BackwardKillWord 
Ctrl+Enter       InsertLineAbove
Shift+Ctrl+Enter InsertLineBelow
Ctrl+Space       MenuComplete
Ctrl+a           SelectAll

**Comment by DropBearHunta** [comment]
These also do not work in powershell 5.1

**Comment by abergs** [comment]
Shift-Tab MenuComplete does not work either

**Comment by Eugeny** [comment]
Ctrl-A should be working in the latest nightly

**Comment by altosaar** [comment]
This still doesn't work :( in Windows 10 with powershell core, on ssh sessions.

**Comment by ShayBox** [comment]
Many shortcuts still don't work 4 years later in Powershell and Powershell Core, does anyone actually use tabby without shortcuts?

**Comment by radeusgd** [comment]
Are there plans to address this? Ctrl+Backwards is super useful in all kinds of CLI work. How do you live without it?

**Comment by Alistair1231** [comment]
`Ctrl + Delete` works to delete the next work.
This should really be addressed however.

**Comment by viva-la-v** [comment]
OK, I tried to enable the ConPTY, and now my Ctrl+H goes to delete the word, and the Ctrl+Backspace still gets a ^H. 😢

**Comment by alexn-s** [comment]
just stumbled upon this issue.
it would be a huge quality of life improvement if this would work.

for now i use ctrl+shift+left to select the last word/s and delete them (needed to remove the tabby shortcut to switch panes/ tabs)

**Comment by tusharsnn** [comment]
Here's a workaround (but not a solution) on Windows:

For deleting a word, Ctrl-W mostly works in shells and other apps like neovim. And to achieve that I used Windows Powertoys to map `Ctrl-Backspace` to `Ctrl-W` only for use within `Tabby`. You can do that easily using Powertoys Keyboard mapping.

This is exactly what `sendSequence()` or `sendInput()`would've done if we had it at our disposal.

**Comment by yoursweetginger** [comment]
Looks like windows users don't use tabby)

**Comment by ShayBox** [comment]
I'd use the quake mode in the Windows terminal if it actually worked reliably, yakuake on Linux.

**Comment by Steltek** [comment]
In my testing (Powershell 7, Windows 11), Ctrl+R does not work correctly. It does work for a single entry, but hitting Ctrl+R does not "go back" further to previous entries. This does work in bare PS7 or the Terminal app.
