### ISSUE TITLE
Inverted text not showing with vibrancy

### ISSUE THREAD

**Issue by martykan** [Eugeny/terminus#646]
With vibrancy enabled on macOS, inverted text doesn't render. Everything works OK with vibrancy off.

<img width="912" alt="screenshot 2019-02-04 at 23 49 24" src="https://user-images.githubusercontent.com/8833813/52242818-ff6e2900-28d7-11e9-96c2-0dae0a45a5a1.png">

**Comment by Eugeny** [comment]
Currently waiting on https://github.com/xtermjs/xterm.js/issues/1898

**Comment by Eugeny** [comment]
Fixed in A94 - release coming up!

**Comment by kachunkachunk** [comment]
Hmm, this is still occurring when enabling Acrylic and using the theme's colors instead of the color scheme's. Currently running A95 (saw it in A94 as well).

**Comment by Eugeny** [comment]
Are you on the xterm or the xterm-webgl frontend?

**Comment by kachunkachunk** [comment]
Sorry for the late update - retesting on A97, and to confirm:
It is being seen on xterm-webgl frontend, as well as hterm. It doesn't seem to matter what theme, trying Original and usually using Relaxed.
Setting the Terminal Background to Theme will do this. Using the Color Scheme's background, won't.

Additional data point:
Regular xterm has been showing me all transparent characters (so, looks like a blank window). The cursor does move around, and content can be copied and pasted elsewhere. Seems all visual here, but I can't really find a config that makes regular xterm work (with SSH or PS). I usually stick with xterm-webgl anyway.
