### ISSUE TITLE
Laggy window behavior on Windows 1903

### ISSUE THREAD

**Issue by lonkaars** [Eugeny/terminus#949]
I just updated my pc to Windows 10 1903, but saw that terminus' window moved incredibly slow. I thought this was a problem with my pc, so I rebooted it. After rebooting, it was still laggy. You can see that shareX completely gives up when moving the window: [link](https://youtu.be/7gpr5XoVDCY).

In this video, you can see my actual cursor appearing once I stopped dragging, while the window keeps moving: [link](https://youtu.be/tTFarBhvMCk)

This might be an issue with windows, but I've also tested it with [fluent terminal](https://github.com/felixse/FluentTerminal), and that app moves fine.

**Comment by spark-integration** [comment]
I have same problem. [Video](https://drive.google.com/file/d/1U9N5f0eNyL716gmivl4kzysaSnt8d6qU/view)

**Comment by cherniy95** [comment]
I have same problem. [Video](https://drive.google.com/file/d/1U9N5f0eNyL716gmivl4kzysaSnt8d6qU/view)

**Comment by lonkaars** [comment]
Turns out, this is a problem with Windows 1903. I found this: [link](https://github.com/riverar/sample-win32-acrylicblur/issues/2).

**Comment by IgnusG** [comment]
Fixed in build [18917](https://aka.ms/AA4pzyf)

**Comment by hv0905** [comment]
Since the bug of windows is still exists, it might be better if Terminus can disable Fluent effect temporarily when draging and re-enable it after the drag completed.
Enable and Disable Arcylic background cost a very little time(< 0.1s)

**Comment by Eugeny** [comment]
@hv0905 good idea

**Comment by Stanzilla** [comment]
I'm on Insider Slow and it fixed the issue in the Windows Terminal for me, but it's still laggy in Terminus.

**Comment by hv0905** [comment]
> I'm on Insider Slow and it fixed the issue in the Windows Terminal for me, but it's still laggy in Terminus.

It seems all UWP apps works just fine.

**Comment by Eugeny** [comment]
@hv0905 done - looking forward to your feedback

**Comment by hv0905** [comment]
Unfortunately, the patch can't fix the bug in windows 10 build 19041. [check out video here](https://edgeneko-bucket.aiursoft.io/Desktop%202020.02.06%20-%2018.28.08.02_Trim.mp4)
This is because [in this code](https://github.com/Eugeny/terminus/commit/1ac22ec5632523f426c04bfad13b54632f8ed11a#diff-1378696b0729d837a5d445e0ecbe2725R7) you disabled the feature at above build 18917.
However the dragging bug is still exist (at lease in build 19041), so we have to keep the arcylic blur disabled when dragging above build 18917.

for @IgnusG 's report, ms just fixed the latency bug in emoji panel (they just directly removed the arcylic effect in emoji panel, very hacking).

**Comment by Eugeny** [comment]
Sorry - I missed the build no in your reply. Is there anything else I could check to detect a "broken" system? (it just works on my recent Insider build)

**Comment by hv0905** [comment]
I couldn't find a way to detect it. But if in your insider build it works fine, maybe 19041 is the last build has the bug. (19041 is the slow ring of windows insider build).

**Comment by WoLfulus** [comment]
Still lagging ( 2004, 19569.1000 )

Only happens if `Background type` is in `Fluent` mode. Blur is ok.

**Comment by xtlsoft** [comment]
![image](https://user-images.githubusercontent.com/16159830/83342899-fa33b980-a326-11ea-8ef2-5f205169f56d.png)
Has the problem.

**Comment by hv0905** [comment]
Confirmed that it only happened when the mouse report rate is too high (~500Hz or more).
It seems that a way should be found to reduce graphics usage when dragging or resizing.
### Something might be helpful: 
https://github.com/Microsoft/vscode/pull/52707
https://github.com/arkenthera/electron-vibrancy

**Comment by Eugeny** [comment]
Since it got broken again in the recent Windows Update, fluent blur is now disabled while the window is being dragging or resized

**Comment by Diaolou** [comment]
I'm a new user evaluating Terminus on a fresh install - for me it's laggy on window drag even with window transparency temporarily disabling on drag.

Other transparent apps (like Windows Terminal, which remains transparent on drag) do not have this issue for me.

Some details that might or might not be helpful:
Terminus version 1.0.134
Windows 10 Pro 20H2 (19042.804)
Dual 4K monitors
Wallpaper Engine live wallpaper running
Mouse polling @ 1000hz

**Comment by sam0x17** [comment]
Broken again for me
